export const ratingMapNames = {
  True: ['True'],
  False: ['False', 'Pants on fire', 'Two Pinocchios', 'Fake'],
  Others: ['Unsupported', 'Unproven', 'Labeled Satire', 'Explanatory', 'In dispute'],
  'Partially false': [
    'No rating',
    'Partially false',
    'Miscaptioned',
    'Misleading',
    'Partially false',
    'Mostly false',
    'Mixture',
    'Mostly true',
    'Misinformation',
    'Misattributed',
    'Partially True',
    'Manipulations',
  ],
}

export const ratingMapRatings = {
  True: 'True',
  False: 'False',
  'Pants on fire': 'False',
  'Two Pinocchios': 'False',
  Fake: 'False',
  Unsupported: 'Others',
  Unproven: 'Others',
  'Labeled Satire': 'Others',
  Explanatory: 'Others',
  'In dispute': 'Others',
  'No rating': 'Partially false',
  'Partially false': 'Partially false',
  Miscaptioned: 'Partially false',
  Misleading: 'Partially false',
  'Mostly false': 'Partially false',
  Mixture: 'Partially false',
  'Mostly true': 'Partially false',
  Misinformation: 'Partially false',
  Misattributed: 'Partially false',
  'Partially True': 'Partially false',
  Manipulations: 'Partially false',
}

export const ratingMapNumbers = {
  true: 3,
  false: 1,
  'pants on fire': 1,
  'two pinocchios': 1,
  fake: 1,
  unsupported: 4,
  unproven: 4,
  'labeled satire': 4,
  explanatory: 4,
  'in dispute': 4,
  'no rating': 2,
  'partially false': 2,
  miscaptioned: 2,
  misleading: 2,
  'mostly false': 2,
  mixture: 2,
  'mostly true': 2,
  misinformation: 2,
  misattributed: 2,
  'partially true': 2,
  manipulations: 2,
}
